// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXpAtDX25fB8Tjt4KhoWaRtTXLwDPPEc',
    appId: '1:1034990466389:web:ef76f556d16478316e6bdc',
    messagingSenderId: '1034990466389',
    projectId: 'the-ev-life',
    authDomain: 'the-ev-life.firebaseapp.com',
    storageBucket: 'the-ev-life.appspot.com',
    measurementId: 'G-VEKTPL0H5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3R2r6H4DmIwRLTy-2kWSZFp7dCBj-FyI',
    appId: '1:1034990466389:android:f9e56f635c140fe56e6bdc',
    messagingSenderId: '1034990466389',
    projectId: 'the-ev-life',
    storageBucket: 'the-ev-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoo7FDuBHww5N3EVREMpo3AZGUvcQkm4',
    appId: '1:1034990466389:ios:79724784489d1f0d6e6bdc',
    messagingSenderId: '1034990466389',
    projectId: 'the-ev-life',
    storageBucket: 'the-ev-life.appspot.com',
    iosClientId: '1034990466389-tsoo2sqn6mhba7gto9ohqajbkn3rv4cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIoo7FDuBHww5N3EVREMpo3AZGUvcQkm4',
    appId: '1:1034990466389:ios:79724784489d1f0d6e6bdc',
    messagingSenderId: '1034990466389',
    projectId: 'the-ev-life',
    storageBucket: 'the-ev-life.appspot.com',
    iosClientId: '1034990466389-tsoo2sqn6mhba7gto9ohqajbkn3rv4cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
